### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by UltimatChamp** [yanggx98/Immersive-Tooltip#1]
<details><summary>Log</summary>

```
[Render thread/ERROR]: Failed to handle packet net.minecraft.class_8733@10193521
java.lang.NullPointerException: Cannot invoke "net.minecraft.client.world.ClientWorld.getTickManager()" because "net.minecraft.client.MinecraftClient.getInstance().world" is null
	at io.github.yanggx98.immersive.tooltip.ImmersiveTooltip$1.getTooltip(ImmersiveTooltip.java:73) ~[immersive-tooltip-1.20.6-1.0.1-beta.jar:?]
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:35) ~[fabric-item-api-v1-8.2.0+5bcea88ab0-50667b80100c7c3b.jar:?]
	at MC/net.minecraft.item.ItemStack.handler$cdn000$fabric-item-api-v1$getTooltip(ItemStack.java:2109) ~[client-intermediary.jar:?]
	at MC/net.minecraft.item.ItemStack.getTooltip(ItemStack.java:796) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.method_1485(MinecraftClient.java:921) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.search.PlainTextSearcherInterface.create(PlainTextSearcherInterface.java:20) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.search.PlainTextSearcher.refresh(PlainTextSearcher.java:26) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.search.SearchManager$RefreshingSearcherProvider.provideSearcher(SearchManager.java:61) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.search.SearchManager.refreshSearch(SearchManager.java:42) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.refreshSearch(MinecraftClient.java:2810) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.method_46740(MinecraftClient.java:942) ~[client-intermediary.jar:?]
	at MC/net.minecraft.item.ItemGroup.reloadSearch(ItemGroup.java:128) ~[client-intermediary.jar:?]
	at MC/net.minecraft.unmapped.C_jvzsxkum.method_57050(C_jvzsxkum.java:24) ~[client-intermediary.jar:?]
	at MC/net.minecraft.unmapped.C_jvzsxkum.method_57053(C_jvzsxkum.java:50) ~[client-intermediary.jar:?]
	at MC/net.minecraft.unmapped.C_jcuvnmyx.method_56585(C_jcuvnmyx.java:70) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.network.ClientConfigurationNetworkHandler.method_57043(ClientConfigurationNetworkHandler.java:117) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.network.ClientConfigurationNetworkHandler.method_57044(ClientConfigurationNetworkHandler.java:109) ~[client-intermediary.jar:?]
	at MC/net.minecraft.client.network.ClientConfigurationNetworkHandler.onFinishConfiguration(ClientConfigurationNetworkHandler.java:117) ~[client-intermediary.jar:?]
	at MC/net.minecraft.network.packet.s2c.configuration.FinishConfigurationS2CPacket.apply(FinishConfigurationS2CPacket.java:22) ~[client-intermediary.jar:?]
	at MC/net.minecraft.network.packet.s2c.configuration.FinishConfigurationS2CPacket.apply(FinishConfigurationS2CPacket.java:8) ~[client-intermediary.jar:?]
	at MC/net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:25) ~[client-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162) [client-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) [client-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136) [client-intermediary.jar:?]
	at MC/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:121) [client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1275) [client-intermediary.jar:?]
	at MC/net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
[Render thread/WARN]: Client disconnected with reason: Network Protocol Error
[Server thread/INFO]: com.mojang.authlib.GameProfile@...[id=...,name=UltimatChamp,properties={textures=[Property[name=textures, value=...]}] lost connection: Disconnected
```
</details>

The crash happens after joining any world the second time upon launching the game.

**Comment by MATRIX-feather** [comment]
I got the same error after joining a survival server, but with a different stack trace:
<details><summary>Details</summary>
<p>

```
[20:53:15] [Render thread/ERROR] (Minecraft) Failed to handle packet net.minecraft.class_8733@1ccc1dcf
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_54719()" because "net.minecraft.class_310.method_1551().field_1687" is null
	at io.github.yanggx98.immersive.tooltip.ImmersiveTooltip$1.getTooltip(ImmersiveTooltip.java:73) ~[immersive-tooltip-1.0.1.i0:0/:?]
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:35) ~[fabric-item-api-v1-8.1.117e985d6ff.i0:0/:?]
	at net.minecraft.class_1799.handler$bhj000$fabric-item-api-v1$getTooltip(class_1799.java:1609) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:796) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_310.method_1485(class_310.java:921) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_7454.method_43796(class_7454.java:20) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1126.method_4799(class_1126.java:26) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1124$class_7457.method_43807(class_1124.java:61) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1124.method_43804(class_1124.java:42) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_310.method_43759(class_310.java:2810) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_310.method_46740(class_310.java:942) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1761.method_47314(class_1761.java:128) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_9175.method_57050(class_9175.java:24) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_9175.method_57053(class_9175.java:50) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_9173.method_56585(class_9173.java:70) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_8674.method_57043(class_8674.java:117) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_8674.method_57044(class_8674.java:109) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_8674.method_52794(class_8674.java:117) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_8733.method_53041(class_8733.java:22) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_8733.method_11054(class_8733.java:8) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:25) ~[transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) [transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) [transformed-mod-minecraft-v1.20.6.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [transformed-mod-minecraft-v1.20.6.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) [quilt-loader-0.26.0-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) [quilt-loader-0.26.0-beta.1.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) [quilt-loader-0.26.0-beta.1.jar:?]
```

</p>
</details>

**Comment by UltimatChamp** [comment]
It's the same actually, but using Quilt mappings, using StackDeofubuscator. _(which makes it much more readable)_

**Comment by yanggx98** [comment]
OK,I think I've solved this problem.Try using 1.0.2 version. thx for your report.
